package py.com.global.educador.jpa.entity;

// Generated Oct 1, 2014 10:48:10 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * ParametroProyecto generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRO_PROYECTO")
public class ParametroProyecto {

	
	private ParametroProyectoId id;
	private Proyecto proyecto;
	private String valor;
	private String descripcion;
	private Boolean editable;
	private Boolean visible;

	public ParametroProyecto() {
	}

	public ParametroProyecto(ParametroProyectoId id, Proyecto proyecto) {
		this.id = id;
		this.proyecto = proyecto;
	}

	public ParametroProyecto(ParametroProyectoId id, Proyecto proyecto,
			String valor, String descripcion, Boolean editable, Boolean visible) {
		this.id = id;
		this.proyecto = proyecto;
		this.valor = valor;
		this.descripcion = descripcion;
		this.editable = editable;
		this.visible = visible;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "parametro", column = @Column(name = "PARAMETRO", nullable = false, length = 300)),
			@AttributeOverride(name = "idProyecto", column = @Column(name = "ID_PROYECTO", nullable = false, precision = 22, scale = 0)) })
	@NotNull
	public ParametroProyectoId getId() {
		return this.id;
	}

	public void setId(ParametroProyectoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROYECTO", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "VALOR", length = 500)
	@Size(max = 500)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "DESCRIPCION", length = 500)
	@Size(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "EDITABLE", precision = 1, scale = 0)
	public Boolean getEditable() {
		return this.editable;
	}

	public void setEditable(Boolean editable) {
		this.editable = editable;
	}

	@Column(name = "VISIBLE", precision = 1, scale = 0)
	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}
	
	
	

}
