package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import py.com.global.educador.gui.utils.EntityInterface;

/**
 * EjecucionSuscriptor generated by hbm2java
 */
@Entity
@Table(name = "EJECUCION_SUSCRIPTOR" )
public class EjecucionSuscriptor extends EntityInterface {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idEjecucionSuscriptor;
	private Suscriptor suscriptor;
	private Modulo modulo;
	private String estadoEjecucion;
	private Date fechaAlta;
	private String motivoCancelacion;
	private Set<EjecucionSuscriptorDetalle> ejecucionSuscriptorDetalles = new HashSet<EjecucionSuscriptorDetalle>(
			0);

	public EjecucionSuscriptor() {
	}

	public EjecucionSuscriptor(Long idEjecucionSuscriptor) {
		this.idEjecucionSuscriptor = idEjecucionSuscriptor;
	}

	public EjecucionSuscriptor(Long idEjecucionSuscriptor,
			Suscriptor suscriptor, Modulo modulo, String estadoEjecucion,
			Date fechaAlta, String motivoCancelacion,
			Set<EjecucionSuscriptorDetalle> ejecucionSuscriptorDetalles) {
		this.idEjecucionSuscriptor = idEjecucionSuscriptor;
		this.suscriptor = suscriptor;
		this.modulo = modulo;
		this.estadoEjecucion = estadoEjecucion;
		this.fechaAlta = fechaAlta;
		this.motivoCancelacion = motivoCancelacion;
		this.ejecucionSuscriptorDetalles = ejecucionSuscriptorDetalles;
	}

	@Id
	@Column(name = "ID_EJECUCION_SUSCRIPTOR", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdEjecucionSuscriptor() {
		return this.idEjecucionSuscriptor;
	}

	public void setIdEjecucionSuscriptor(Long idEjecucionSuscriptor) {
		this.idEjecucionSuscriptor = idEjecucionSuscriptor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SUSCRIPTOR")
	public Suscriptor getSuscriptor() {
		return this.suscriptor;
	}

	public void setSuscriptor(Suscriptor suscriptor) {
		this.suscriptor = suscriptor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MODULO")
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@Column(name = "ESTADO_EJECUCION", length = 30)
	@Size(max = 30)
	public String getEstadoEjecucion() {
		return this.estadoEjecucion;
	}

	public void setEstadoEjecucion(String estadoEjecucion) {
		this.estadoEjecucion = estadoEjecucion;
	}

	 
	@Column(name = "FECHA_ALTA", length = 7)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "MOTIVO_CANCELACION", length = 200)
	@Size(max = 200)
	public String getMotivoCancelacion() {
		return this.motivoCancelacion;
	}

	public void setMotivoCancelacion(String motivoCancelacion) {
		this.motivoCancelacion = motivoCancelacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ejecucionSuscriptor")
	public Set<EjecucionSuscriptorDetalle> getEjecucionSuscriptorDetalles() {
		return this.ejecucionSuscriptorDetalles;
	}

	public void setEjecucionSuscriptorDetalles(
			Set<EjecucionSuscriptorDetalle> ejecucionSuscriptorDetalles) {
		this.ejecucionSuscriptorDetalles = ejecucionSuscriptorDetalles;
	}

	@Override
	@Transient
	public Serializable getId() {
		return getIdEjecucionSuscriptor();
	}

}
