package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import java.lang.Long;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * EvaluacionSuscriptor generated by hbm2java
 */
@Entity
@Table(name = "EVALUACION_SUSCRIPTOR" )
public class EvaluacionSuscriptor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idEvaluacionSuscriptor;
	private Evaluacion evaluacion;
	private Suscriptor suscriptor;
	private Pregunta pregunta;
	private EjecucionSuscriptorDetalle ejecucionSuscriptorDetalle;
	private Respuesta respuesta;
	private Boolean respuestaCorrecta;
	private String estadoEvaluacion;
	private Date fechaAlta;
	private Date fechaRespuesta;
	private Date fechaEnvioPregunta;
	private Long intento;
	private String respuestaSenderSmsc;
	private String estadoEnvio;
	private String respuestaAbierta;

	public EvaluacionSuscriptor() {
	}

	public EvaluacionSuscriptor(Long idEvaluacionSuscriptor) {
		this.idEvaluacionSuscriptor = idEvaluacionSuscriptor;
	}

	public EvaluacionSuscriptor(Long idEvaluacionSuscriptor,
			Evaluacion evaluacion, Suscriptor suscriptor, Pregunta pregunta,
			EjecucionSuscriptorDetalle ejecucionSuscriptorDetalle,
			Long idRespuesta, Boolean respuestaCorrecta,
			String estadoEvaluacion, Date fechaAlta, Date fechaRespuesta,
			Date fechaEnvioPregunta, Long intento,
			String respuestaSenderSmsc, String estadoEnvio) {
		this.idEvaluacionSuscriptor = idEvaluacionSuscriptor;
		this.evaluacion = evaluacion;
		this.suscriptor = suscriptor;
		this.pregunta = pregunta;
		this.ejecucionSuscriptorDetalle = ejecucionSuscriptorDetalle;
		
		this.respuestaCorrecta = respuestaCorrecta;
		this.estadoEvaluacion = estadoEvaluacion;
		this.fechaAlta = fechaAlta;
		this.fechaRespuesta = fechaRespuesta;
		this.fechaEnvioPregunta = fechaEnvioPregunta;
		this.intento = intento;
		this.respuestaSenderSmsc = respuestaSenderSmsc;
		this.estadoEnvio = estadoEnvio;
	}

	@Id
	@Column(name = "ID_EVALUACION_SUSCRIPTOR", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdEvaluacionSuscriptor() {
		return this.idEvaluacionSuscriptor;
	}

	public void setIdEvaluacionSuscriptor(Long idEvaluacionSuscriptor) {
		this.idEvaluacionSuscriptor = idEvaluacionSuscriptor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EVALUACION")
	public Evaluacion getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(Evaluacion evaluacion) {
		this.evaluacion = evaluacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SUSCRIPTOR")
	public Suscriptor getSuscriptor() {
		return this.suscriptor;
	}

	public void setSuscriptor(Suscriptor suscriptor) {
		this.suscriptor = suscriptor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PREGUNTA")
	public Pregunta getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(Pregunta pregunta) {
		this.pregunta = pregunta;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RESPUESTA")
	public Respuesta getRespuesta() {
		return respuesta;
	}

	public void setRespuesta(Respuesta respuesta) {
		this.respuesta = respuesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EJECUCION_DETALLE")
	public EjecucionSuscriptorDetalle getEjecucionSuscriptorDetalle() {
		return this.ejecucionSuscriptorDetalle;
	}

	public void setEjecucionSuscriptorDetalle(
			EjecucionSuscriptorDetalle ejecucionSuscriptorDetalle) {
		this.ejecucionSuscriptorDetalle = ejecucionSuscriptorDetalle;
	}


	@Column(name = "RESPUESTA_CORRECTA", precision = 1, scale = 0)
	public Boolean getRespuestaCorrecta() {
		return this.respuestaCorrecta;
	}

	public void setRespuestaCorrecta(Boolean respuestaCorrecta) {
		this.respuestaCorrecta = respuestaCorrecta;
	}

	@Column(name = "ESTADO_EVALUACION", length = 50)
	@Size(max = 50)
	public String getEstadoEvaluacion() {
		return this.estadoEvaluacion;
	}

	public void setEstadoEvaluacion(String estadoEvaluacion) {
		this.estadoEvaluacion = estadoEvaluacion;
	}

	 
	@Column(name = "FECHA_ALTA", length = 7)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	 
	@Column(name = "FECHA_RESPUESTA", length = 7)
	public Date getFechaRespuesta() {
		return this.fechaRespuesta;
	}

	public void setFechaRespuesta(Date fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}

	 
	@Column(name = "FECHA_ENVIO_PREGUNTA", length = 7)
	public Date getFechaEnvioPregunta() {
		return this.fechaEnvioPregunta;
	}

	public void setFechaEnvioPregunta(Date fechaEnvioPregunta) {
		this.fechaEnvioPregunta = fechaEnvioPregunta;
	}

	@Column(name = "INTENTO", precision = 22, scale = 0)
	public Long getIntento() {
		return this.intento;
	}

	public void setIntento(Long intento) {
		this.intento = intento;
	}

	@Column(name = "RESPUESTA_SENDER_SMSC", length = 500)
	@Size(max = 500)
	public String getRespuestaSenderSmsc() {
		return this.respuestaSenderSmsc;
	}

	public void setRespuestaSenderSmsc(String respuestaSenderSmsc) {
		this.respuestaSenderSmsc = respuestaSenderSmsc;
	}

	@Column(name = "ESTADO_ENVIO", length = 50)
	@Size(max = 50)
	public String getEstadoEnvio() {
		return this.estadoEnvio;
	}

	public void setEstadoEnvio(String estadoEnvio) {
		this.estadoEnvio = estadoEnvio;
	}

	@Column(name="RESPUESTA_ABIERTA")
	public String getRespuestaAbierta() {
		return respuestaAbierta;
	}

	public void setRespuestaAbierta(String respuestaAbierta) {
		this.respuestaAbierta = respuestaAbierta;
	}
	
	

}
