package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * LogClientResponse generated by hbm2java
 */
@Entity
@Table(name = "LOG_CLIENT_RESPONSE" )
public class LogClientResponse implements java.io.Serializable {

	private BigDecimal idLogClientResponse;
	private Suscriptor suscriptor;
	private String mensaje;
	private Date fechaRecepcion;
	private String numero;
	private String numeroCorto;

	public LogClientResponse() {
	}

	public LogClientResponse(BigDecimal idLogClientResponse) {
		this.idLogClientResponse = idLogClientResponse;
	}

	public LogClientResponse(BigDecimal idLogClientResponse,
			Suscriptor suscriptor, String mensaje, Date fechaRecepcion,
			String numero, String numeroCorto) {
		this.idLogClientResponse = idLogClientResponse;
		this.suscriptor = suscriptor;
		this.mensaje = mensaje;
		this.fechaRecepcion = fechaRecepcion;
		this.numero = numero;
		this.numeroCorto = numeroCorto;
	}

	@Id
	@Column(name = "ID_LOG_CLIENT_RESPONSE", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	public BigDecimal getIdLogClientResponse() {
		return this.idLogClientResponse;
	}

	public void setIdLogClientResponse(BigDecimal idLogClientResponse) {
		this.idLogClientResponse = idLogClientResponse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SUSCRIPTOR")
	public Suscriptor getSuscriptor() {
		return this.suscriptor;
	}

	public void setSuscriptor(Suscriptor suscriptor) {
		this.suscriptor = suscriptor;
	}

	@Column(name = "MENSAJE", length = 200)
	@Size(max = 200)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	 
	@Column(name = "FECHA_RECEPCION", length = 7)
	public Date getFechaRecepcion() {
		return this.fechaRecepcion;
	}

	public void setFechaRecepcion(Date fechaRecepcion) {
		this.fechaRecepcion = fechaRecepcion;
	}

	@Column(name = "NUMERO", length = 50)
	@Size(max = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "NUMERO_CORTO", length = 20)
	@Size(max = 20)
	public String getNumeroCorto() {
		return this.numeroCorto;
	}

	public void setNumeroCorto(String numeroCorto) {
		this.numeroCorto = numeroCorto;
	}

}
