package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import py.com.global.educador.gui.utils.EntityInterface;

/**
 * LogSmsIn generated by hbm2java
 */
@Entity
@Table(name = "LOG_SMS_IN" )
public class LogSmsIn extends EntityInterface {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idLogSmsIn;
	private String numeroDestino;
	private String numeroOrigen;
	private String mensaje;
	private Date fechaRecepcion;
	private String jmsMessageId;

	public LogSmsIn() {
	}

	public LogSmsIn(Long idLogSmsIn) {
		this.idLogSmsIn = idLogSmsIn;
	}

	public LogSmsIn(Long idLogSmsIn, String numeroDestino,
			String numeroOrigen, String mensaje, Date fechaRecepcion,
			String jmsMessageId) {
		this.idLogSmsIn = idLogSmsIn;
		this.numeroDestino = numeroDestino;
		this.numeroOrigen = numeroOrigen;
		this.mensaje = mensaje;
		this.fechaRecepcion = fechaRecepcion;
		this.jmsMessageId = jmsMessageId;
	}

	@Id
	@Column(name = "ID_LOG_SMS_IN", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdLogSmsIn() {
		return this.idLogSmsIn;
	}

	public void setIdLogSmsIn(Long idLogSmsIn) {
		this.idLogSmsIn = idLogSmsIn;
	}

	@Column(name = "NUMERO_DESTINO", length = 30)
	@Size(max = 30)
	public String getNumeroDestino() {
		return this.numeroDestino;
	}

	public void setNumeroDestino(String numeroDestino) {
		this.numeroDestino = numeroDestino;
	}

	@Column(name = "NUMERO_ORIGEN", length = 30)
	@Size(max = 30)
	public String getNumeroOrigen() {
		return this.numeroOrigen;
	}

	public void setNumeroOrigen(String numeroOrigen) {
		this.numeroOrigen = numeroOrigen;
	}

	@Column(name = "MENSAJE", length = 200)
	@Size(max = 200)
	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

	 
	@Column(name = "FECHA_RECEPCION", length = 7)
	public Date getFechaRecepcion() {
		return this.fechaRecepcion;
	}

	public void setFechaRecepcion(Date fechaRecepcion) {
		this.fechaRecepcion = fechaRecepcion;
	}

	@Column(name = "JMS_MESSAGE_ID", length = 100)
	@Size(max = 100)
	public String getJmsMessageId() {
		return this.jmsMessageId;
	}

	public void setJmsMessageId(String jmsMessageId) {
		this.jmsMessageId = jmsMessageId;
	}

	@Override
	@Transient
	public Serializable getId() {
		return getIdLogSmsIn();
	}

}
