package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import py.com.global.educador.gui.utils.EntityInterface;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "PROYECTO" )
public class Proyecto extends EntityInterface {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idProyecto;
	private String nombre;
	private String descripcion;
	private String objetivos;
	private Date fechaInicio;
	private Date fechaFin;
	private Usuario usuarioAlta;
	private Usuario usuarioModificacion;
	private Date fechaAlta;
	private Date fechaModificacion;
	private String estadoProyecto;
	private String estadoRegistro;
	private String numeroCorto;
	private Set<Modulo> modulos = new HashSet<Modulo>(0);
	private Set<SuscriptorProyecto> suscriptorProyectos = new HashSet<SuscriptorProyecto>(
			0);
	private Set<ParametroProyecto> parametroProyectos = new HashSet<ParametroProyecto>(
			0);
	
	public Proyecto() {
	}

	public Proyecto(Long idProyecto) {
		this.idProyecto = idProyecto;
	}

	public Proyecto(Long idProyecto, String nombre, String descripcion,
			String objetivos, Date fechaInicio, Date fechaFin,
			Usuario usuarioAlta, Usuario usuarioModificacion, Date fechaAlta,
			Date fechaModificacion, String estadoProyecto,
			String estadoRegistro, String numeroCorto, Set<Modulo> modulos,
			Set<SuscriptorProyecto> suscriptorProyectos) {
		this.idProyecto = idProyecto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.objetivos = objetivos;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.usuarioAlta = usuarioAlta;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaAlta = fechaAlta;
		this.fechaModificacion = fechaModificacion;
		this.estadoProyecto = estadoProyecto;
		this.estadoRegistro = estadoRegistro;
		this.numeroCorto = numeroCorto;
		this.modulos = modulos;
		this.suscriptorProyectos = suscriptorProyectos;
	}

	@Id
	@SequenceGenerator(name="PROYECTO_IDPROYECTO_GENERATOR", sequenceName="PROYECTO_ID_SEQ",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PROYECTO_IDPROYECTO_GENERATOR")
	@Column(name = "ID_PROYECTO", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Long idProyecto) {
		this.idProyecto = idProyecto;
	}

	@Column(name = "NOMBRE", length = 100)
	@Size(max = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "DESCRIPCION", length = 500)
	@Size(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "OBJETIVOS", length = 500)
	@Size(max = 500)
	public String getObjetivos() {
		return this.objetivos;
	}

	public void setObjetivos(String objetivos) {
		this.objetivos = objetivos;
	}

	 
	@Column(name = "FECHA_INICIO", length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	 
	@Column(name = "FECHA_FIN", length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_ALTA")
	public Usuario getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_MODIFICACION")
	public Usuario getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	 
	@Column(name = "FECHA_ALTA", length = 7)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	 
	@Column(name = "FECHA_MODIFICACION", length = 7)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ESTADO_PROYECTO", length = 30)
	@Size(max = 30)
	public String getEstadoProyecto() {
		return this.estadoProyecto;
	}

	public void setEstadoProyecto(String estadoProyecto) {
		this.estadoProyecto = estadoProyecto;
	}

	@Column(name = "ESTADO_REGISTRO", length = 30)
	@Size(max = 30)
	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	@Column(name = "NUMERO_CORTO", length = 30)
	@Size(max = 30)
	public String getNumeroCorto() {
		return this.numeroCorto;
	}

	public void setNumeroCorto(String numeroCorto) {
		this.numeroCorto = numeroCorto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proyecto")
	public Set<Modulo> getModulos() {
		return this.modulos;
	}

	public void setModulos(Set<Modulo> modulos) {
		this.modulos = modulos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proyecto")
	public Set<SuscriptorProyecto> getSuscriptorProyectos() {
		return this.suscriptorProyectos;
	}

	public void setSuscriptorProyectos(
			Set<SuscriptorProyecto> suscriptorProyectos) {
		this.suscriptorProyectos = suscriptorProyectos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proyecto")
	public Set<ParametroProyecto> getParametroProyectos() {
		return this.parametroProyectos;
	}

	public void setParametroProyectos(Set<ParametroProyecto> parametroProyectos) {
		this.parametroProyectos = parametroProyectos;
	}
	
	
	@Override
	@Transient
	public Serializable getId() {
		return getIdProyecto();
	}

}
