package py.com.global.educador.gui.entity;

// Generated Jul 22, 2014 7:06:37 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

import py.com.global.educador.gui.utils.EntityInterface;

/**
 * ReporteDetalles generated by hbm2java
 */
@Entity
@Table(name = "REPORTE_DETALLES")
public class ReporteDetalles extends EntityInterface {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idDetalle;
	private String  vista;
	private String nombreCampo;
	private String valor;
	private Long orden;

	public ReporteDetalles() {
	}

	

	@Id
	@Column(name = "ID_DETALLE", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdDetalle() {
		return this.idDetalle;
	}

	public void setIdDetalle(Long idDetalle) {
		this.idDetalle = idDetalle;
	}

	
	@Column(name = "VISTA", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getVista() {
		return vista;
	}



	public void setVista(String vista) {
		this.vista = vista;
	}



	@Column(name = "NOMBRE_CAMPO", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNombreCampo() {
		return this.nombreCampo;
	}

	public void setNombreCampo(String nombreCampo) {
		this.nombreCampo = nombreCampo;
	}

	@Column(name = "VALOR", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "ORDEN", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getOrden() {
		return this.orden;
	}

	public void setOrden(Long orden) {
		this.orden = orden;
	}

	@Override
	@Transient
	public Serializable getId() {
		return getIdDetalle();
	}

}
