package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import py.com.global.educador.gui.utils.EntityInterface;

/**
 * SuscriptorProyecto generated by hbm2java
 */
@Entity
@Table(name = "SUSCRIPTOR_PROYECTO" )
public class SuscriptorProyecto extends EntityInterface {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SuscriptorProyectoId id;
	private Proyecto proyecto;
	private Suscriptor suscriptor;
	private Modulo modulo;
	private String estadoSuscriptorProyecto;
	private String estadoSuscriptorModulo;

	public SuscriptorProyecto() {
	}

	public SuscriptorProyecto(SuscriptorProyectoId id, Proyecto proyecto,
			Suscriptor suscriptor, String estadoSuscriptorProyecto) {
		this.id = id;
		this.proyecto = proyecto;
		this.suscriptor = suscriptor;
		this.estadoSuscriptorProyecto = estadoSuscriptorProyecto;
	}

	public SuscriptorProyecto(SuscriptorProyectoId id, Proyecto proyecto,
			Suscriptor suscriptor, Modulo modulo,
			String estadoSuscriptorProyecto, String estadoSuscriptorModulo) {
		this.id = id;
		this.proyecto = proyecto;
		this.suscriptor = suscriptor;
		this.modulo = modulo;
		this.estadoSuscriptorProyecto = estadoSuscriptorProyecto;
		this.estadoSuscriptorModulo = estadoSuscriptorModulo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSuscriptor", column = @Column(name = "ID_SUSCRIPTOR", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idProyecto", column = @Column(name = "ID_PROYECTO", nullable = false, precision = 22, scale = 0)) })
	@NotNull
	public SuscriptorProyectoId getId() {
		return this.id;
	}

	public void setId(SuscriptorProyectoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROYECTO", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SUSCRIPTOR", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Suscriptor getSuscriptor() {
		return this.suscriptor;
	}

	public void setSuscriptor(Suscriptor suscriptor) {
		this.suscriptor = suscriptor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MODULO_ACTUAL")
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@Column(name = "ESTADO_SUSCRIPTOR_PROYECTO",  length = 30)
	@Size(max = 30)
	public String getEstadoSuscriptorProyecto() {
		return this.estadoSuscriptorProyecto;
	}

	public void setEstadoSuscriptorProyecto(String estadoSuscriptorProyecto) {
		this.estadoSuscriptorProyecto = estadoSuscriptorProyecto;
	}

	@Column(name = "ESTADO_SUSCRIPTOR_MODULO", length = 30)
	@Size(max = 30)
	public String getEstadoSuscriptorModulo() {
		return this.estadoSuscriptorModulo;
	}

	public void setEstadoSuscriptorModulo(String estadoSuscriptorModulo) {
		this.estadoSuscriptorModulo = estadoSuscriptorModulo;
	}

}
