package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import java.lang.Long;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;

import py.com.global.educador.gui.utils.EntityInterfaceId;

/**
 * SuscriptorProyectoId generated by hbm2java
 */
@Embeddable
public class SuscriptorProyectoId extends EntityInterfaceId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idSuscriptor;
	private Long idProyecto;

	public SuscriptorProyectoId() {
	}

	public SuscriptorProyectoId(Long idSuscriptor, Long idProyecto) {
		this.idSuscriptor = idSuscriptor;
		this.idProyecto = idProyecto;
	}

	@Column(name = "ID_SUSCRIPTOR", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdSuscriptor() {
		return this.idSuscriptor;
	}

	public void setIdSuscriptor(Long idSuscriptor) {
		this.idSuscriptor = idSuscriptor;
	}

	@Column(name = "ID_PROYECTO", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Long idProyecto) {
		this.idProyecto = idProyecto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SuscriptorProyectoId))
			return false;
		SuscriptorProyectoId castOther = (SuscriptorProyectoId) other;

		return ((this.getIdSuscriptor() == castOther.getIdSuscriptor()) || (this
				.getIdSuscriptor() != null
				&& castOther.getIdSuscriptor() != null && this
				.getIdSuscriptor().equals(castOther.getIdSuscriptor())))
				&& ((this.getIdProyecto() == castOther.getIdProyecto()) || (this
						.getIdProyecto() != null
						&& castOther.getIdProyecto() != null && this
						.getIdProyecto().equals(castOther.getIdProyecto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdSuscriptor() == null ? 0 : this.getIdSuscriptor()
						.hashCode());
		result = 37
				* result
				+ (getIdProyecto() == null ? 0 : this.getIdProyecto()
						.hashCode());
		return result;
	}

}
