package py.com.global.educador.gui.entity;

// Generated Aug 21, 2014 6:09:06 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import py.com.global.educador.gui.utils.EntityInterface;

/**
 * Tip generated by hbm2java
 */
@Entity
@Table(name = "TIP" )
public class Tip extends EntityInterface {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idTip;
	private Modulo modulo;
	private String contenido;
	private Date fechaAlta;
	private Usuario usuarioAlta;
	private Date fechaModificacion;
	private Usuario usuarioModificacion;
	private String estadoRegistro;
	private Set<PlanificacionEnvio> planificacionEnvios = new HashSet<PlanificacionEnvio>(
			0);
	private Set<EjecucionSuscriptorDetalle> ejecucionSuscriptorDetalles = new HashSet<EjecucionSuscriptorDetalle>(
			0);

	public Tip() {
	}

	public Tip(Long idTip) {
		this.idTip = idTip;
	}

	public Tip(Long idTip, Modulo modulo, String contenido,
			Date fechaAlta, Usuario usuarioAlta, Date fechaModificacion,
			Usuario usuarioModificacion, String estadoRegistro,
			Set<PlanificacionEnvio> planificacionEnvios,
			Set<EjecucionSuscriptorDetalle> ejecucionSuscriptorDetalles) {
		this.idTip = idTip;
		this.modulo = modulo;
		this.contenido = contenido;
		this.fechaAlta = fechaAlta;
		this.usuarioAlta = usuarioAlta;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModificacion = usuarioModificacion;
		this.estadoRegistro = estadoRegistro;
		this.planificacionEnvios = planificacionEnvios;
		this.ejecucionSuscriptorDetalles = ejecucionSuscriptorDetalles;
	}

	@Id
	@Column(name = "ID_TIP", unique = true, nullable = false, precision = 22, scale = 0)
	@SequenceGenerator(name="TIP_IDTIP_GENERATOR", sequenceName="TIP_ID_SEQ")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="TIP_IDTIP_GENERATOR")
	@NotNull
	public Long getIdTip() {
		return this.idTip;
	}

	public void setIdTip(Long idTip) {
		this.idTip = idTip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MODULO")
	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	@Column(name = "CONTENIDO", length = 200)
	@Size(max = 200)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	 
	@Column(name = "FECHA_ALTA", length = 7)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_ALTA")
	public Usuario getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(Usuario usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	 
	@Column(name = "FECHA_MODIFICACION", length = 7)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_MODIFICACION")
	public Usuario getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Usuario usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ESTADO_REGISTRO", length = 30)
	@Size(max = 30)
	public String getEstadoRegistro() {
		return this.estadoRegistro;
	}

	public void setEstadoRegistro(String estadoRegistro) {
		this.estadoRegistro = estadoRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tip")
	public Set<PlanificacionEnvio> getPlanificacionEnvios() {
		return this.planificacionEnvios;
	}

	public void setPlanificacionEnvios(
			Set<PlanificacionEnvio> planificacionEnvios) {
		this.planificacionEnvios = planificacionEnvios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tip")
	public Set<EjecucionSuscriptorDetalle> getEjecucionSuscriptorDetalles() {
		return this.ejecucionSuscriptorDetalles;
	}

	public void setEjecucionSuscriptorDetalles(
			Set<EjecucionSuscriptorDetalle> ejecucionSuscriptorDetalles) {
		this.ejecucionSuscriptorDetalles = ejecucionSuscriptorDetalles;
	}

	@Override
	@Transient
	public Serializable getId() {
		return getIdTip();
	}

}
